import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";


const mont = Montserrat({
  subsets: ["latin"],
  weight: ['400']
})


export const metadata: Metadata = {
  title: "Asaba.Inc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mont.className} antialiased`}
      >
        <div className=" w-full bg-white overflow-x-hidden">
         {children}
        </div>
      </body>
    </html>
  );
}
